# Generated by Django 3.0.7 on 2020-06-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='Введение')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание ')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация ')),
            ],
            options={
                'verbose_name': 'Программы кусров',
                'verbose_name_plural': 'Программа курса',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя ')),
                ('content', models.TextField(verbose_name='Описание')),
                ('rate', models.IntegerField(verbose_name='Оценка')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='SelectionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(db_index=True, max_length=50, verbose_name='Название Курсов')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя преподавателя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия преподавателя')),
                ('experience', models.TextField(max_length=150, verbose_name='Опыт')),
            ],
            options={
                'verbose_name': 'Преподаватели',
                'verbose_name_plural': 'Преподаватель ',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('order_number', models.IntegerField(verbose_name='Порядковый номер')),
                ('link', models.TextField(verbose_name='Название')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('language', models.CharField(db_index=True, max_length=30, verbose_name='Язык')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Требование к курсу')),
                ('sale', models.IntegerField(default=0, verbose_name='Скидка в %')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('img', models.ImageField(height_field=100, upload_to='images/', width_field=100)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.CourseOutline', verbose_name='Описание')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Feedback', verbose_name='Отзывы')),
                ('teacher', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='main.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['feedback__rate'],
            },
        ),
    ]
